### ISSUE TITLE
NullPointerException in FrustumAccessor during world entry

### ISSUE THREAD

**Issue by YuJianghan** [fzzyhmstrs/pc#13]
### Issue Description:
I'm encountering an intermittent crash when entering a world with the `particle_core` mod version 0.1.2 on Minecraft version 1.20.4_Fabric_0.15.11. The crash does not occur every time, but it happens often enough to be problematic.

#### Crash Details:
The crash log indicates a `NullPointerException` related to the `frustum` object being null. Below is the relevant portion of the crash report:

```
java.lang.NullPointerException: Cannot invoke "me.fzzyhmstrs.particle_core.mixins.FrustumAccessor.getFrustumIntersection()" because "this.frustum" is null
	at net.minecraft.class_702.wrapWithCondition$flh000$particle_core$cullParticles(class_702.java:4653)
	at net.minecraft.class_702.method_3049(class_702.java:448)
	at net.minecraft.class_761.handler$edk000$iris$renderOpaqueParticles(class_761.java:14200)
	at net.minecraft.class_761.method_22710(class_761.java:1036)
	at net.minecraft.class_757.method_3188(class_757.java:1098)
```

#### Steps to Reproduce:
1. Launch Minecraft with the `particle_core` mod installed.
2. Enter a world.
3. Sometimes, the game crashes with the above `NullPointerException`.

#### Additional Information:
- Mod Version: `particle_core-0.1.2+1.20`
- Minecraft Version: `1.20.4_Fabric_0.15.11`

This issue involves multiple mixins, including `FrustumAccessor`, `ParticleManagerFrustumMixin`, `MixinParticleEngine`, and `MixinParticleManager`.

I've ensured all mods are up-to-date and compatible with each other. The crash still occurs intermittently, and it's specifically related to the rendering of particles.

Please let me know if you need any additional information or if there are any known workarounds for this issue.

[crash-2024-06-23_21.46.45-client.txt](https://github.com/user-attachments/files/15944899/crash-2024-06-23_21.46.45-client.txt)

**Comment by fzzyhmstrs** [comment]
I have recently released a new 1.20.4 version of PC, and would be curious if the problem is resolved or not with it
